### ISSUE TITLE
cant seem to get git to clone project

### ISSUE THREAD

**Issue by shawnggraham** [ajbogh/norman#11]
This could just be me doing something wrong as im not all that familar with git but when i follow the install section of the README and run the git clone command i get this error.
git clone git@github.com:ajbogh/norman.git
Cloning into 'norman'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ajbogh** [comment]
It seems as though your ssh key may need to be updated. Please follow these instructions:

https://vitalflux.com/solution-to-permission-denied-public-key-for-git-clone/

More info:

https://help.github.com/articles/error-permission-denied-publickey/
